[package]
name = "utils"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
# Workspace
rpc         = { path    = "../rpc" }

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
hyper       = "0.13"
lapin       = "1.6"
lazy_static = "1.4"
metrics     = { version = "0.12", features = ["std"] }
rdkafka     = { version = "0.24", features = ["cmake-build"] }
reqwest     = { version = "0.10", features = ["json"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = { version = "1.0", features = ["raw_value"] }
structopt   = "0.3"
thiserror   = "1.0"
tokio       = { version = "0.2", features = ["rt-core"] }
tokio-amqp  = "0.1"
tracing     = "0.1"
url         = "2.2"
uuid        = { version = "0.8", features = ["v1", "serde"] }
vec_map     = "0.8"
async-stream            = "0.3"
futures-util            = "0.3"
metrics-exporter-http   = "0.3"
metrics-runtime         = "0.13"
tonic                   = "0.3"
tracing-futures         = "0.2"
tracing-subscriber      = "0.2"
metrics-observer-prometheus         = "0.1"

[dev-dependencies]
test-case = "1.1"
tokio       = { version = "0.2", features = ["rt-threaded", "macros", "sync"] }
