[tasks.pack-wasm]
script = "wasm-pack build . --target web --out-name wasm --out-dir www/wasm"

[tasks.clean-wasm]
script = "rm -rf static/wasm"

[tasks.build]
dependencies = ["clean-wasm", "pack-wasm"]
command = "cargo"
args = ["build"]

[tasks.start]
dependencies = ["build"]
command = "http-server"
args = ["www"]
